### ISSUE TITLE
No provider for CookieService!

### ISSUE THREAD

**Issue by YuriFontella** [salemdar/ngx-cookie#2]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => check the FAQ and search github for a similar issue or PR before submitting
[ ] support request => check the FAQ and search github for a similar issue before submitting
[ ] feature request
```

**Current behavior**

```
EXCEPTION: Uncaught (in promise): Error: DI Error
Error: DI Error
    at NoProviderError.ZoneAwareError (http://127.0.0.1:4200/polyfills.bundle.js:3527:33)
    at NoProviderError.BaseError [as constructor] (http://127.0.0.1:4200/vendor.bundle.js:30862:16)
    at NoProviderError.AbstractProviderError [as constructor] (http://127.0.0.1:4200/vendor.bundle.js:61336:16)
    at new NoProviderError (http://127.0.0.1:4200/vendor.bundle.js:61398:16)
    at ReflectiveInjector_._throwOrNull (http://127.0.0.1:4200/vendor.bundle.js:83888:19)
    at ReflectiveInjector_._getByKeyDefault (http://127.0.0.1:4200/vendor.bundle.js:83927:25)
    at ReflectiveInjector_._getByKey (http://127.0.0.1:4200/vendor.bundle.js:83859:25)
    at ReflectiveInjector_.get (http://127.0.0.1:4200/vendor.bundle.js:83728:21)
    at AppModuleInjector.get (/AppModule/module.ngfactory.js:264:124)
    at AppModuleInjector.getInternal (/AppModule/module.ngfactory.js:456:54)
    at AppModuleInjector.NgModuleInjector.get (http://127.0.0.1:4200/vendor.bundle.js:62271:44)
    at CompiledTemplate.proxyViewClass.AppView.injectorGet (http://127.0.0.1:4200/vendor.bundle.js:84663:45)
    at CompiledTemplate.proxyViewClass.DebugAppView.injectorGet (http://127.0.0.1:4200/vendor.bundle.js:85091:49)
    at ElementInjector.get (http://127.0.0.1:4200/vendor.bundle.js:84167:27)
    at ReflectiveInjector_._getByKeyDefault (http://127.0.0.1:4200/vendor.bundle.js:83924:24)
ErrorHandler.handleError @ error_handler.js:54
next @ application_ref.js:348
schedulerFn @ async.js:93
SafeSubscriber.__tryOrUnsub @ Subscriber.js:234
SafeSubscriber.next @ Subscriber.js:183
Subscriber._next @ Subscriber.js:125
Subscriber.next @ Subscriber.js:89
Subject.next @ Subject.js:55
EventEmitter.emit @ async.js:79
NgZone.triggerError @ ng_zone.js:333
onHandleError @ ng_zone.js:294
webpackJsonp.979.ZoneDelegate.handleError @ zone.js:334
webpackJsonp.979.Zone.runGuarded @ zone.js:142
_loop_1 @ zone.js:540
drainMicroTaskQueue @ zone.js:549
error_handler.js:59 ORIGINAL STACKTRACE:
ErrorHandler.handleError @ error_handler.js:59
next @ application_ref.js:348
schedulerFn @ async.js:93
SafeSubscriber.__tryOrUnsub @ Subscriber.js:234
SafeSubscriber.next @ Subscriber.js:183
Subscriber._next @ Subscriber.js:125
Subscriber.next @ Subscriber.js:89
Subject.next @ Subject.js:55
EventEmitter.emit @ async.js:79
NgZone.triggerError @ ng_zone.js:333
onHandleError @ ng_zone.js:294
webpackJsonp.979.ZoneDelegate.handleError @ zone.js:334
webpackJsonp.979.Zone.runGuarded @ zone.js:142
_loop_1 @ zone.js:540
drainMicroTaskQueue @ zone.js:549
error_handler.js:60 Error: Uncaught (in promise): Error: DI Error
Error: DI Error
    at NoProviderError.ZoneAwareError (zone.js:958)
    at NoProviderError.BaseError [as constructor] (errors.js:22)
    at NoProviderError.AbstractProviderError [as constructor] (reflective_errors.js:54)
    at new NoProviderError (reflective_errors.js:116)
    at ReflectiveInjector_._throwOrNull (reflective_injector.js:485)
    at ReflectiveInjector_._getByKeyDefault (reflective_injector.js:524)
    at ReflectiveInjector_._getByKey (reflective_injector.js:456)
    at ReflectiveInjector_.get (reflective_injector.js:325)
    at AppModuleInjector.get (module.ngfactory.js:264)
    at AppModuleInjector.getInternal (module.ngfactory.js:456)
    at AppModuleInjector.NgModuleInjector.get (ng_module_factory.js:139)
    at CompiledTemplate.proxyViewClass.AppView.injectorGet (view.js:152)
    at CompiledTemplate.proxyViewClass.DebugAppView.injectorGet (view.js:580)
    at ElementInjector.get (element_injector.js:32)
    at ReflectiveInjector_._getByKeyDefault (reflective_injector.js:521)
    at resolvePromise (zone.js:643) [angular]
    at resolvePromise (zone.js:619) [angular]
    at :4200/polyfills.bundle.js:3248:17 [angular]
    at Object.onInvokeTask (ng_zone.js:264) [angular]
    at ZoneDelegate.webpackJsonp.979.ZoneDelegate.invokeTask (zone.js:362) [angular]
    at Zone.webpackJsonp.979.Zone.runTask (zone.js:166) [<root> => angular]
    at drainMicroTaskQueue (zone.js:529) [<root>]
ErrorHandler.handleError @ error_handler.js:60
next @ application_ref.js:348
schedulerFn @ async.js:93
SafeSubscriber.__tryOrUnsub @ Subscriber.js:234
SafeSubscriber.next @ Subscriber.js:183
Subscriber._next @ Subscriber.js:125
Subscriber.next @ Subscriber.js:89
Subject.next @ Subject.js:55
EventEmitter.emit @ async.js:79
NgZone.triggerError @ ng_zone.js:333
onHandleError @ ng_zone.js:294
webpackJsonp.979.ZoneDelegate.handleError @ zone.js:334
webpackJsonp.979.Zone.runGuarded @ zone.js:142
_loop_1 @ zone.js:540
drainMicroTaskQueue @ zone.js:549
zone.js:516 Unhandled Promise rejection: No provider for CookieService! ; Zone: angular ; Task: Promise.then ; Value: NoProviderError {__zone_symbol__error: Error: DI Error
    at NoProviderError.ZoneAwareError (http://127.0.0.1:4200/polyfills.bundle.js:352…, _nativeError: ZoneAwareError, keys: Array[1], injectors: Array[1], __zone_symbol__message: "No provider for CookieService!"…}__zone_symbol__error: Error: DI Error
    at NoProviderError.ZoneAwareError (http://127.0.0.1:4200/polyfills.bundle.js:3527:33)
    at NoProviderError.BaseError [as constructor] (http://127.0.0.1:4200/vendor.bundle.js:30862:16)
    at NoProviderError.AbstractProviderError [as constructor] (http://127.0.0.1:4200/vendor.bundle.js:61336:16)
    at new NoProviderError (http://127.0.0.1:4200/vendor.bundle.js:61398:16)
    at ReflectiveInjector_._throwOrNull (http://127.0.0.1:4200/vendor.bundle.js:83888:19)
    at ReflectiveInjector_._getByKeyDefault (http://127.0.0.1:4200/vendor.bundle.js:83927:25)
    at ReflectiveInjector_._getByKey (http://127.0.0.1:4200/vendor.bundle.js:83859:25)
    at ReflectiveInjector_.get (http://127.0.0.1:4200/vendor.bundle.js:83728:21)
    at AppModuleInjector.get (/AppModule/module.ngfactory.js:264:124)
    at AppModuleInjector.getInternal (/AppModule/module.ngfactory.js:456:54)
    at AppModuleInjector.NgModuleInjector.get (http://127.0.0.1:4200/vendor.bundle.js:62271:44)
    at CompiledTemplate.proxyViewClass.AppView.injectorGet (http://127.0.0.1:4200/vendor.bundle.js:84663:45)
    at CompiledTemplate.proxyViewClass.DebugAppView.injectorGet (http://127.0.0.1:4200/vendor.bundle.js:85091:49)
    at ElementInjector.get (http://127.0.0.1:4200/vendor.bundle.js:84167:27)
    at ReflectiveInjector_._getByKeyDefault (http://127.0.0.1:4200/vendor.bundle.js:83924:24)__zone_symbol__message: "No provider for CookieService!"__zone_symbol__stack: "Error: DI Error↵    at NoProviderError.ZoneAwareError (http://127.0.0.1:4200/polyfills.bundle.js:3527:33)↵    at NoProviderError.BaseError [as constructor] (http://127.0.0.1:4200/vendor.bundle.js:30862:16)↵    at NoProviderError.AbstractProviderError [as constructor] (http://127.0.0.1:4200/vendor.bundle.js:61336:16)↵    at new NoProviderError (http://127.0.0.1:4200/vendor.bundle.js:61398:16)↵    at ReflectiveInjector_._throwOrNull (http://127.0.0.1:4200/vendor.bundle.js:83888:19)↵    at ReflectiveInjector_._getByKeyDefault (http://127.0.0.1:4200/vendor.bundle.js:83927:25)↵    at ReflectiveInjector_._getByKey (http://127.0.0.1:4200/vendor.bundle.js:83859:25)↵    at ReflectiveInjector_.get (http://127.0.0.1:4200/vendor.bundle.js:83728:21)↵    at AppModuleInjector.get (/AppModule/module.ngfactory.js:264:124)↵    at AppModuleInjector.getInternal (/AppModule/module.ngfactory.js:456:54)↵    at AppModuleInjector.NgModuleInjector.get (http://127.0.0.1:4200/vendor.bundle.js:62271:44)↵    at CompiledTemplate.proxyViewClass.AppView.injectorGet (http://127.0.0.1:4200/vendor.bundle.js:84663:45)↵    at CompiledTemplate.proxyViewClass.DebugAppView.injectorGet (http://127.0.0.1:4200/vendor.bundle.js:85091:49)↵    at ElementInjector.get (http://127.0.0.1:4200/vendor.bundle.js:84167:27)↵    at ReflectiveInjector_._getByKeyDefault (http://127.0.0.1:4200/vendor.bundle.js:83924:24)"_nativeError: ZoneAwareErrorconstructResolvingMessage: (keys)injectors: Array[1]keys: Array[1]message: (...)get message: ()set message: (value)name: (...)get name: ()set name: (value)originalStack: (...)get originalStack: ()set originalStack: (value)stack: (...)get stack: ()set stack: (value)toSource: ()toString: ()zoneAwareStack: (...)get zoneAwareStack: ()set zoneAwareStack: (value)__proto__: AbstractProviderError Error: DI Error
    at NoProviderError.ZoneAwareError (http://127.0.0.1:4200/polyfills.bundle.js:3527:33)
    at NoProviderError.BaseError [as constructor] (http://127.0.0.1:4200/vendor.bundle.js:30862:16)
    at NoProviderError.AbstractProviderError [as constructor] (http://127.0.0.1:4200/vendor.bundle.js:61336:16)
    at new NoProviderError (http://127.0.0.1:4200/vendor.bundle.js:61398:16)
    at ReflectiveInjector_._throwOrNull (http://127.0.0.1:4200/vendor.bundle.js:83888:19)
    at ReflectiveInjector_._getByKeyDefault (http://127.0.0.1:4200/vendor.bundle.js:83927:25)
    at ReflectiveInjector_._getByKey (http://127.0.0.1:4200/vendor.bundle.js:83859:25)
    at ReflectiveInjector_.get (http://127.0.0.1:4200/vendor.bundle.js:83728:21)
    at AppModuleInjector.get (/AppModule/module.ngfactory.js:264:124)
    at AppModuleInjector.getInternal (/AppModule/module.ngfactory.js:456:54)
    at AppModuleInjector.NgModuleInjector.get (http://127.0.0.1:4200/vendor.bundle.js:62271:44)
    at CompiledTemplate.proxyViewClass.AppView.injectorGet (http://127.0.0.1:4200/vendor.bundle.js:84663:45)
    at CompiledTemplate.proxyViewClass.DebugAppView.injectorGet (http://127.0.0.1:4200/vendor.bundle.js:85091:49)
    at ElementInjector.get (http://127.0.0.1:4200/vendor.bundle.js:84167:27)
    at ReflectiveInjector_._getByKeyDefault (http://127.0.0.1:4200/vendor.bundle.js:83924:24)
consoleError @ zone.js:516
_loop_1 @ zone.js:545
drainMicroTaskQueue @ zone.js:549
zone.js:518 ZoneAwareError {__zone_symbol__error: Error: Uncaught (in promise): Error: DI Error
Error: DI Error
    at NoProviderError.ZoneAwareError …, rejection: NoProviderError, promise: ZoneAwarePromise, zone: Zone, task: ZoneTask…}__zone_symbol__error: Error: Uncaught (in promise): Error: DI Error
Error: DI Error
    at NoProviderError.ZoneAwareError (http://127.0.0.1:4200/polyfills.bundle.js:3527:33)
    at NoProviderError.BaseError [as constructor] (http://127.0.0.1:4200/vendor.bundle.js:30862:16)
    at NoProviderError.AbstractProviderError [as constructor] (http://127.0.0.1:4200/vendor.bundle.js:61336:16)
    at new NoProviderError (http://127.0.0.1:4200/vendor.bundle.js:61398:16)
    at ReflectiveInjector_._throwOrNull (http://127.0.0.1:4200/vendor.bundle.js:83888:19)
    at ReflectiveInjector_._getByKeyDefault (http://127.0.0.1:4200/vendor.bundle.js:83927:25)
    at ReflectiveInjector_._getByKey (http://127.0.0.1:4200/vendor.bundle.js:83859:25)
    at ReflectiveInjector_.get (http://127.0.0.1:4200/vendor.bundle.js:83728:21)
    at AppModuleInjector.get (/AppModule/module.ngfactory.js:264:124)
    at AppModuleInjector.getInternal (/AppModule/module.ngfactory.js:456:54)
    at AppModuleInjector.NgModuleInjector.get (http://127.0.0.1:4200/vendor.bundle.js:62271:44)
    at CompiledTemplate.proxyViewClass.AppView.injectorGet (http://127.0.0.1:4200/vendor.bundle.js:84663:45)
    at CompiledTemplate.proxyViewClass.DebugAppView.injectorGet (http://127.0.0.1:4200/vendor.bundle.js:85091:49)
    at ElementInjector.get (http://127.0.0.1:4200/vendor.bundle.js:84167:27)
    at ReflectiveInjector_._getByKeyDefault (http://127.0.0.1:4200/vendor.bundle.js:83924:24)
    at NoProviderError.ZoneAwareError (http://127.0.0.1:4200/polyfills.bundle.js:3527:33)
    at NoProviderError.BaseError [as constructor] (http://127.0.0.1:4200/vendor.bundle.js:30862:16)
    at NoProviderError.AbstractProviderError [as constructor] (http://127.0.0.1:4200/vendor.bundle.js:61336:16)
    at new NoProviderError (http://127.0.0.1:4200/vendor.bundle.js:61398:16)
    at ReflectiveInjector_._throwOrNull (http://127.0.0.1:4200/vendor.bundle.js:83888:19)
    at ReflectiveInjector_._getByKeyDefault (http://127.0.0.1:4200/vendor.bundle.js:83927:25)
    at ReflectiveInjector_._getByKey (http://127.0.0.1:4200/vendor.bundle.js:83859:25)
    at ReflectiveInjector_.get (http://127.0.0.1:4200/vendor.bundle.js:83728:21)
    at AppModuleInjector.get (/AppModule/module.ngfactory.js:264:124)
    at AppModuleInjector.getInternal (/AppModule/module.ngfactory.js:456:54)
    at AppModuleInjector.NgModuleInjector.get (http://127.0.0.1:4200/vendor.bundle.js:62271:44)
    at CompiledTemplate.proxyViewClass.AppView.injectorGet (http://127.0.0.1:4200/vendor.bundle.js:84663:45)
    at CompiledTemplate.proxyViewClass.DebugAppView.injectorGet (http://127.0.0.1:4200/vendor.bundle.js:85091:49)
    at ElementInjector.get (http://127.0.0.1:4200/vendor.bundle.js:84167:27)
    at ReflectiveInjector_._getByKeyDefault (http://127.0.0.1:4200/vendor.bundle.js:83924:24)
    at resolvePromise (http://127.0.0.1:4200/polyfills.bundle.js:3212:31) [angular]
    at resolvePromise (http://127.0.0.1:4200/polyfills.bundle.js:3188:17) [angular]
    at http://127.0.0.1:4200/polyfills.bundle.js:3248:17 [angular]
    at Object.onInvokeTask (http://127.0.0.1:4200/vendor.bundle.js:32515:37) [angular]
    at ZoneDelegate.webpackJsonp.979.ZoneDelegate.invokeTask (http://127.0.0.1:4200/polyfills.bundle.js:2931:36) [angular]
    at Zone.webpackJsonp.979.Zone.runTask (http://127.0.0.1:4200/polyfills.bundle.js:2735:47) [<root> => angular]
    at drainMicroTaskQueue (http://127.0.0.1:4200/polyfills.bundle.js:3098:35) [<root>]__zone_symbol__message: "Uncaught (in promise): Error: DI Error↵Error: DI Error↵    at NoProviderError.ZoneAwareError (http://127.0.0.1:4200/polyfills.bundle.js:3527:33)↵    at NoProviderError.BaseError [as constructor] (http://127.0.0.1:4200/vendor.bundle.js:30862:16)↵    at NoProviderError.AbstractProviderError [as constructor] (http://127.0.0.1:4200/vendor.bundle.js:61336:16)↵    at new NoProviderError (http://127.0.0.1:4200/vendor.bundle.js:61398:16)↵    at ReflectiveInjector_._throwOrNull (http://127.0.0.1:4200/vendor.bundle.js:83888:19)↵    at ReflectiveInjector_._getByKeyDefault (http://127.0.0.1:4200/vendor.bundle.js:83927:25)↵    at ReflectiveInjector_._getByKey (http://127.0.0.1:4200/vendor.bundle.js:83859:25)↵    at ReflectiveInjector_.get (http://127.0.0.1:4200/vendor.bundle.js:83728:21)↵    at AppModuleInjector.get (/AppModule/module.ngfactory.js:264:124)↵    at AppModuleInjector.getInternal (/AppModule/module.ngfactory.js:456:54)↵    at AppModuleInjector.NgModuleInjector.get (http://127.0.0.1:4200/vendor.bundle.js:62271:44)↵    at CompiledTemplate.proxyViewClass.AppView.injectorGet (http://127.0.0.1:4200/vendor.bundle.js:84663:45)↵    at CompiledTemplate.proxyViewClass.DebugAppView.injectorGet (http://127.0.0.1:4200/vendor.bundle.js:85091:49)↵    at ElementInjector.get (http://127.0.0.1:4200/vendor.bundle.js:84167:27)↵    at ReflectiveInjector_._getByKeyDefault (http://127.0.0.1:4200/vendor.bundle.js:83924:24)"__zone_symbol__stack: "Error: Uncaught (in promise): Error: DI Error↵Error: DI Error↵    at NoProviderError.ZoneAwareError (http://127.0.0.1:4200/polyfills.bundle.js:3527:33)↵    at NoProviderError.BaseError [as constructor] (http://127.0.0.1:4200/vendor.bundle.js:30862:16)↵    at NoProviderError.AbstractProviderError [as constructor] (http://127.0.0.1:4200/vendor.bundle.js:61336:16)↵    at new NoProviderError (http://127.0.0.1:4200/vendor.bundle.js:61398:16)↵    at ReflectiveInjector_._throwOrNull (http://127.0.0.1:4200/vendor.bundle.js:83888:19)↵    at ReflectiveInjector_._getByKeyDefault (http://127.0.0.1:4200/vendor.bundle.js:83927:25)↵    at ReflectiveInjector_._getByKey (http://127.0.0.1:4200/vendor.bundle.js:83859:25)↵    at ReflectiveInjector_.get (http://127.0.0.1:4200/vendor.bundle.js:83728:21)↵    at AppModuleInjector.get (/AppModule/module.ngfactory.js:264:124)↵    at AppModuleInjector.getInternal (/AppModule/module.ngfactory.js:456:54)↵    at AppModuleInjector.NgModuleInjector.get (http://127.0.0.1:4200/vendor.bundle.js:62271:44)↵    at CompiledTemplate.proxyViewClass.AppView.injectorGet (http://127.0.0.1:4200/vendor.bundle.js:84663:45)↵    at CompiledTemplate.proxyViewClass.DebugAppView.injectorGet (http://127.0.0.1:4200/vendor.bundle.js:85091:49)↵    at ElementInjector.get (http://127.0.0.1:4200/vendor.bundle.js:84167:27)↵    at ReflectiveInjector_._getByKeyDefault (http://127.0.0.1:4200/vendor.bundle.js:83924:24)↵    at resolvePromise (http://127.0.0.1:4200/polyfills.bundle.js:3212:31) [angular]↵    at resolvePromise (http://127.0.0.1:4200/polyfills.bundle.js:3188:17) [angular]↵    at http://127.0.0.1:4200/polyfills.bundle.js:3248:17 [angular]↵    at Object.onInvokeTask (http://127.0.0.1:4200/vendor.bundle.js:32515:37) [angular]↵    at ZoneDelegate.webpackJsonp.979.ZoneDelegate.invokeTask (http://127.0.0.1:4200/polyfills.bundle.js:2931:36) [angular]↵    at Zone.webpackJsonp.979.Zone.runTask (http://127.0.0.1:4200/polyfills.bundle.js:2735:47) [<root> => angular]↵    at drainMicroTaskQueue (http://127.0.0.1:4200/polyfills.bundle.js:3098:35) [<root>]"message: (...)get message: ()set message: (value)name: (...)get name: ()set name: (value)originalStack: (...)get originalStack: ()set originalStack: (value)promise: ZoneAwarePromiserejection: NoProviderErrorstack: (...)get stack: ()set stack: (value)task: ZoneTasktoSource: ()toString: ()zone: ZonezoneAwareStack: (...)get zoneAwareStack: ()set zoneAwareStack: (value)__proto__: Object
consoleError @ zone.js:518
_loop_1 @ zone.js:545
drainMicroTaskQueue @ zone.js:549
```

**Reproduction of the problem**

It generates the cookie without errors, but the error happens when accessing the component Profile.

https://gist.github.com/YuriFontella/2d7580e43acad37cbf716d15b6bc3a11

Some type of route incompatibility?
I am using CookieService within a service.

**What is the motivation / use case for changing the behavior?**

I declare the CookieService provider everywhere possible

**Please tell us about your environment:**

* **ngx-cookie version:** 1.0.0

* **Angular version:** 2.4.9
 
* **Browser:** [all]

**Comment by ManojlovicMilos** [comment]
Same issue

**Comment by YuriFontella** [comment]
Refactoring in my project and the problem did not arise.
