### ISSUE TITLE
Errors when updated from v5.0.0 to v5.0.2

### ISSUE THREAD

**Issue by kuncevic** [salemdar/ngx-cookie#282]
1. Upgrade the library from 5.0.0 to 5.0.2
2. Run prerender 

**Expected behavior**
There should not be any errors

I do have 2 types of errors now.

### Type 1. Initiating things in ngOnInit

I have this code that works in case of v5.0.0

```
  ngOnInit() {
    if (this.router.url.indexOf(AngularWorkshopRouting.path.closed) >= 0) {
      this.page = WaitingListPageInfo.getData('closed');
    } else if (
      this.router.url.indexOf(AngularWorkshopRouting.path.waitlist) >= 0
    ) {
      this.page = WaitingListPageInfo.getData('waiting');
    }
  }
```
Basically here I do populating the object page that used in my html template this way:
```
  <h1>{{ page.meta.title }}</h1>
```

Now I am getting an error in console when trying to prerender the app
```
ERROR TypeError: Cannot read property 'meta' of undefined
    at PaymentSuccessComponent_Template (/Volumes/Work/Work/Projects/xyz/dist/xyz/server/projects-xyz-src-app-courses-courses-module.js:1:33185)
    at executeTemplate (/Volumes/Work/Work/Projects/xyz/dist/xyz/server/main.js:1:1595341)
    at refreshView (/Volumes/Work/Work/Projects/xyz/dist/xyz/server/main.js:1:1591769)
    at refreshComponent (/Volumes/Work/Work/Projects/xyz/dist/xyz/server/main.js:1:1608127)
    at refreshChildComponents (/Volumes/Work/Work/Projects/xyz/dist/xyz/server/main.js:1:1594019)
    at refreshView (/Volumes/Work/Work/Projects/xyz/dist/xyz/server/main.js:1:1594061)
    at refreshEmbeddedViews (/Volumes/Work/Work/Projects/xyz/dist/xyz/server/main.js:1:1592907)
    at refreshView (/Volumes/Work/Work/Projects/xyz/dist/xyz/server/main.js:1:1592989)
    at refreshComponent (/Volumes/Work/Work/Projects/xyz/dist/xyz/server/main.js:1:1608127)
    at refreshChildComponents (/Volumes/Work/Work/Projects/xyz/dist/xyz/server/main.js:1:1594019)
ERROR TypeError: Cannot read property 'meta' of undefined
    at PaymentSuccessComponent_Template (/Volumes/Work/Work/Projects/xyz/dist/xyz/server/projects-xyz-src-app-courses-courses-module.js:1:33185)
    at executeTemplate (/Volumes/Work/Work/Projects/xyz/dist/xyz/server/main.js:1:1595341)
    at refreshView (/Volumes/Work/Work/Projects/xyz/dist/xyz/server/main.js:1:1591769)
    at refreshComponent (/Volumes/Work/Work/Projects/xyz/dist/xyz/server/main.js:1:1608127)
    at refreshChildComponents (/Volumes/Work/Work/Projects/xyz/dist/xyz/server/main.js:1:1594019)
    at refreshView (/Volumes/Work/Work/Projects/xyz/dist/xyz/server/main.js:1:1594061)
    at refreshEmbeddedViews (/Volumes/Work/Work/Projects/xyz/dist/xyz/server/main.js:1:1592907)
    at refreshView (/Volumes/Work/Work/Projects/xyz/dist/xyz/server/main.js:1:1592989)
    at refreshComponent (/Volumes/Work/Work/Projects/xyz/dist/xyz/server/main.js:1:1608127)
    at refreshChildComponents (/Volumes/Work/Work/Projects/xyz/dist/xyz/server/main.js:1:1594019)
```

### Type 2. TypeError: Cannot read property 'getHeader' of null
That is seems related to the ngx-cookie-backend service

```
Prerendering 32 route(s) to /Volumes/Work/Work/Projects/xyz/dist/xyz...ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'getHeader' of null
TypeError: Cannot read property 'getHeader' of null
    at ngx_cookie_backend_CookieBackendWriterService.getNormalizedResponseCookies (/Volumes/Work/Work/Projects/xyz/dist/xyz/server/main.js:1:3061602)
    at ngx_cookie_backend_CookieBackendWriterService.readAllAsString (/Volumes/Work/Work/Projects/xyz/dist/xyz/server/main.js:1:3061405)
    at CookieService.getAll (/Volumes/Work/Work/Projects/xyz/dist/xyz/server/main.js:1:403976)
    at CookieService.get (/Volumes/Work/Work/Projects/xyz/dist/xyz/server/main.js:1:403284)
    at ReferralService.get (/Volumes/Work/Work/Projects/xyz/dist/xyz/server/main.js:1:414706)
    at GuardService.canActivate (/Volumes/Work/Work/Projects/xyz/dist/xyz/server/main.js:1:415071)
    at /Volumes/Work/Work/ProERROR Error: Uncaught (in promise): TypeError: Cannot read property 'getHeader' of null
TypeError: Cannot read property 'getHeader' of null
    at ngx_cookie_backend_CookieBackendWriterService.getNormalizedResponseCookies (/Volumes/Work/Work/Projects/xyz/dist/xyz/server/main.js:1:3061602)
    at ngx_cookie_backend_CookieBackendWriterService.readAllAsString (/Volumes/Work/Work/Projects/xyz/dist/xyz/server/main.js:1:3061405)
    at CookieService.getAll (/Volumes/Work/Work/Projects/xyz/dist/xyz/server/main.js:1:403976)
    at CookieService.get (/Volumes/Work/Work/Projects/xyz/dist/xyz/server/main.js:1:403284)
    at ReferralService.get (/Volumes/Work/Work/Projects/xyz/dist/xyz/server/main.js:1:414706)
    at GuardService.canActivate (/Volumes/Work/Work/Projects/xyz/dist/xyz/server/main.js:1:415071)
    at /Volumes/Work/Work/Projects/xyz/dist/xyz/server/main.js:1:3642110
    at Observable_Observable._subscribe (/Volumes/Work/Work/Projects/xyz/dist/xyz/server/main.js:1:859887)
    at Observable_Observable._trySubscribe (/Volumes/Work/Work/Projects/xyz/dist/xyz/server/main.js:1:745882)
    at Observable_Observable.subscribe (/Volumes/Work/Work/Projects/xyz/dist/xyz/server/main.js:1:745664)
    at resolvePromise (/Volumes/Work/Work/Projects/xyz/dist/xyz/server/main.js:1:1412787)
    at resolvePromise (/Volumes/Work/Work/Projects/xyz/dist/xyz/server/main.js:1:1411774)
    at /Volumes/Work/Work/Projects/xyz/dist/xyz/server/main.js:1:1414461
    at ZoneDelegate.invokeTask (/Volumes/Work/Work/Projects/xyz/dist/xyz/server/main.js:1:1397036)
    at Object.onInvokeTask (/Volumes/Work/Work/Projects/xyz/dist/xyz/server/main.js:1:1844744)
    at ZoneDelegate.invokeTask (/Volumes/Work/Work/Projects/xyz/dist/xyz/server/main.js:1:1396926)
    at Zone.runTask (/Volumes/Work/Work/Projects/xyz/dist/xyz/server/main.js:1:1389601)
    at drainMicroTaskQueue (/Volumes/Work/Work/Projects/xyz/dist/xyz/server/main.js:1:1400644) {
  rejection: TypeError: Cannot read property 'getHeader' of null
      at ngx_cookie_backend_CookieBackendWriterService.getNormalizedResponseCookies (/Volumes/Work/Work/Projects/xyz/dist/xyz/server/main.js:1:3061602)
      at ngx_cookie_backend_CookieBackendWriterService.readAllAsString (/Volumes/Work/Work/Projects/xyz/dist/xyz/server/main.js:1:3061405)
      at CookieService.getAll (/Volumes/Work/Work/Projects/xyz/dist/xyz/server/main.js:1:403976)
      at CookieService.get (/Volumes/Work/Work/Projects/xyz/dist/xyz/server/main.js:1:403284)
      at ReferralService.get (/Volumes/Work/Work/Projects/xyz/dist/xyz/server/main.js:1:414706)
      at GuardService.canActivate (/Volumes/Work/Work/Projects/xyz/dist/xyz/server/main.js:1:415071)
      at /Volumes/Work/Work/Projects/xyz/dist/xyz/server/main.js:1:3642110
      at Observable_Observable._subscribe (/Volumes/Work/Work/Projects/xyz/dist/xyz/server/main.js:1:859887)
      at Observable_Observable._trySubscribe (/Volumes/Work/Work/Projects/xyz/dist/xyz/server/main.js:1:745882)
      at Observable_Observable.subscribe (/Volumes/Work/Work/Projects/xyz/dist/xyz/server/main.js:1:745664),
  promise: ZoneAwarePromise [Promise] {
    __zone_symbol__state: 0,
    __zone_symbol__value: TypeError: Cannot read property 'getHeader' of null
        at ngx_cookie_backend_CookieBackendWriterService.getNormalizedResponseCookies (/Volumes/Work/Work/Projects/xyz/dist/xyz/server/main.js:1:3061602)
        at ngx_cookie_backend_CookieBackendWriterService.readAllAsString (/Volumes/Work/Work/Projects/xyz/dist/xyz/server/main.js:1:3061405)
        at CookieService.getAll (/Volumes/Work/Work/Projects/xyz/dist/xyz/server/main.js:1:403976)
        at CookieService.get (/Volumes/Work/Work/Projects/xyz/dist/xyz/server/main.js:1:403284)
        at ReferralService.get (/Volumes/Work/Work/Projects/xyz/dist/xyz/server/main.js:1:414706)
        at GuardService.canActivate (/Volumes/Work/Work/Projects/xyz/dist/xyz/server/main.js:1:415071)
        at /Volumes/Work/Work/Projects/xyz/dist/xyz/server/main.js:1:3642110
        at Observable_Observable._subscribe (/Volumes/Work/Work/Projects/xyz/dist/xyz/server/main.js:1:859887)
        at Observable_Observable._trySubscribe (/Volumes/Work/Work/Projects/xyz/dist/xyz/server/main.js:1:745882)
        at Observable_Observable.subscribe (/Volumes/Work/Work/Projects/xyz/dist/xyz/server/main.js:1:745664)
  },
  zone: Zone {
    _parent: Zone {
      _parent: null,
      _name: '<root>',
      _properties: {},
      _zoneDelegate: [ZoneDelegate]
    },
    _name: 'angular',
    _properties: { isAngularZone: true },
    _zoneDelegate: ZoneDelegate {
      _taskCounts: [Object],
      zone: [Circular],
      _parentDelegate: [ZoneDelegate],
      _forkZS: null,
      _forkDlgt: null,
      _forkCurrZone: null,
      _interceptZS: null,
      _interceptDlgt: null,
      _interceptCurrZone: null,
      _invokeZS: [Object],
      _invokeDlgt: [ZoneDelegate],
      _invokeCurrZone: [Circular],
      _handleErrorZS: [Object],
      _handleErrorDlgt: [ZoneDelegate],
      _handleErrorCurrZone: [Circular],
      _scheduleTaskZS: [Object],
      _scheduleTaskDlgt: [ZoneDelegate],
      _scheduleTaskCurrZone: [Circular],
      _invokeTaskZS: [Object],
      _invokeTaskDlgt: [ZoneDelegate],
      _invokeTaskCurrZone: [Circular],
      _cancelTaskZS: [Object],
      _cancelTaskDlgt: [ZoneDelegate],
      _cancelTaskCurrZone: [Circular],
      _hasTaskZS: [Object],
      _hasTaskDlgt: [ZoneDelegate],
      _hasTaskDlgtOwner: [Circular],
      _hasTaskCurrZone: [Circular]
    }
  },
  task: ZoneTask {
    _zone: Zone {
      _parent: [Zone],
      _name: 'angular',
      _properties: [Object],
      _zoneDelegate: [ZoneDelegate]
    },
    runCount: 0,
    _zoneDelegates: null,
    _state: 'notScheduled',
    type: 'microTask',
    source: 'Promise.then',
    data: ZoneAwarePromise [Promise] {
      __zone_symbol__state: 0,
      __zone_symbol__value: TypeError: Cannot read property 'getHeader' of null
          at ngx_cookie_backend_CookieBackendWriterService.getNormalizedResponseCookies (/Volumes/Work/Work/Projects/xyz/dist/xyz/server/main.js:1:3061602)
          at ngx_cookie_backend_CookieBackendWriterService.readAllAsString (/Volumes/Work/Work/Projects/xyz/dist/xyz/server/main.js:1:3061405)
          at CookieService.getAll (/Volumes/Work/Work/Projects/xyz/dist/xyz/server/main.js:1:403976)
          at CookieService.get (/Volumes/Work/Work/Projects/xyz/dist/xyz/server/main.js:1:403284)
          at ReferralService.get (/Volumes/Work/Work/Projects/xyz/dist/xyz/server/main.js:1:414706)
          at GuardService.canActivate (/Volumes/Work/Work/Projects/xyz/dist/xyz/server/main.js:1:415071)
          at /Volumes/Work/Work/Projects/xyz/dist/xyz/server/main.js:1:3642110
          at Observable_Observable._subscribe (/Volumes/Work/Work/Projects/xyz/dist/xyz/server/main.js:1:859887)
          at Observable_Observable._trySubscribe (/Volumes/Work/Work/Projects/xyz/dist/xyz/server/main.js:1:745882)
          at Observable_Observable.subscribe (/Volumes/Work/Work/Projects/xyz/dist/xyz/server/main.js:1:745664)
    },
    scheduleFn: undefined,
    cancelFn: undefined,
    callback: [Function],
    invoke: [Function]
  }
}
jects/xyz/dist/xyz/server/main.js:1:3642110
    at Observable_Observable._subscribe (/Volumes/Work/Work/Projects/xyz/dist/xyz/server/main.js:1:859887)
    at Observable_Observable._trySubscribe (/Volumes/Work/Work/Projects/xyz/dist/xyz/server/main.js:1:745882)
    at Observable_Observable.subscribe (/Volumes/Work/Work/Projects/xyz/dist/xyz/server/main.js:1:745664)
    at resolvePromise (/Volumes/Work/Work/Projects/xyz/dist/xyz/server/main.js:1:1412787)
    at resolvePromise (/Volumes/Work/Work/Projects/xyz/dist/xyz/server/main.js:1:1411774)
    at /Volumes/Work/Work/Projects/xyz/dist/xyz/server/main.js:1:1414461
    at ZoneDelegate.invokeTask (/Volumes/Work/Work/Projects/xyz/dist/xyz/server/main.js:1:1397036)
    at Object.onInvokeTask (/Volumes/Work/Work/Projects/xyz/dist/xyz/server/main.js:1:1844744)
    at ZoneDelegate.invokeTask (/Volumes/Work/Work/Projects/xyz/dist/xyz/server/main.js:1:1396926)
    at Zone.runTask (/Volumes/Work/Work/Projects/xyz/dist/xyz/server/main.js:1:1389601)
    at drainMicroTaskQueue (/Volumes/Work/Work/Projects/xyz/dist/xyz/server/main.js:1:1400644) {
  rejection: TypeError: Cannot read property 'getHeader' of null
      at ngx_cookie_backend_CookieBackendWriterService.getNormalizedResponseCookies (/Volumes/Work/Work/Projects/xyz/dist/xyz/server/main.js:1:3061602)
      at ngx_cookie_backend_CookieBackendWriterService.readAllAsString (/Volumes/Work/Work/Projects/xyz/dist/xyz/server/main.js:1:3061405)
      at CookieService.getAll (/Volumes/Work/Work/Projects/xyz/dist/xyz/server/main.js:1:403976)
      at CookieService.get (/Volumes/Work/Work/Projects/xyz/dist/xyz/server/main.js:1:403284)
      at ReferralService.get (/Volumes/Work/Work/Projects/xyz/dist/xyz/server/main.js:1:414706)
      at GuardService.canActivate (/Volumes/Work/Work/Projects/xyz/dist/xyz/server/main.js:1:415071)
      at /Volumes/Work/Work/Projects/xyz/dist/xyz/server/main.js:1:3642110
      at Observable_Observable._subscribe (/Volumes/Work/Work/Projects/xyz/dist/xyz/server/main.js:1:859887)
      at Observable_Observable._trySubscribe (/Volumes/Work/Work/Projects/xyz/dist/xyz/server/main.js:1:745882)
      at Observable_Observable.subscribe (/Volumes/Work/Work/Projects/xyz/dist/xyz/server/main.js:1:745664),
  promise: ZoneAwarePromise [Promise] {
    __zone_symbol__state: 0,
    __zone_symbol__value: TypeError: Cannot read property 'getHeader' of null
        at ngx_cookie_backend_CookieBackendWriterService.getNormalizedResponseCookies (/Volumes/Work/Work/Projects/xyz/dist/xyz/server/main.js:1:3061602)
        at ngx_cookie_backend_CookieBackendWriterService.readAllAsString (/Volumes/Work/Work/Projects/xyz/dist/xyz/server/main.js:1:3061405)
        at CookieService.getAll (/Volumes/Work/Work/Projects/xyz/dist/xyz/server/main.js:1:403976)
        at CookieService.get (/Volumes/Work/Work/Projects/xyz/dist/xyz/server/main.js:1:403284)
        at ReferralService.get (/Volumes/Work/Work/Projects/xyz/dist/xyz/server/main.js:1:414706)
        at GuardService.canActivate (/Volumes/Work/Work/Projects/xyz/dist/xyz/server/main.js:1:415071)
        at /Volumes/Work/Work/Projects/xyz/dist/xyz/server/main.js:1:3642110
        at Observable_Observable._subscribe (/Volumes/Work/Work/Projects/xyz/dist/xyz/server/main.js:1:859887)
        at Observable_Observable._trySubscribe (/Volumes/Work/Work/Projects/xyz/dist/xyz/server/main.js:1:745882)
        at Observable_Observable.subscribe (/Volumes/Work/Work/Projects/xyz/dist/xyz/server/main.js:1:745664)
  },
  zone: Zone {
    _parent: Zone {
      _parent: null,
      _name: '<root>',
      _properties: {},
      _zoneDelegate: [ZoneDelegate]
    },
    _name: 'angular',
    _properties: { isAngularZone: true },
    _zoneDelegate: ZoneDelegate {
      _taskCounts: [Object],
      zone: [Circular],
      _parentDelegate: [ZoneDelegate],
      _forkZS: null,
      _forkDlgt: null,
      _forkCurrZone: null,
      _interceptZS: null,
      _interceptDlgt: null,
      _interceptCurrZone: null,
      _invokeZS: [Object],
      _invokeDlgt: [ZoneDelegate],
      _invokeCurrZone: [Circular],
      _handleErrorZS: [Object],
      _handleErrorDlgt: [ZoneDelegate],
      _handleErrorCurrZone: [Circular],
      _scheduleTaskZS: [Object],
      _scheduleTaskDlgt: [ZoneDelegate],
      _scheduleTaskCurrZone: [Circular],
      _invokeTaskZS: [Object],
      _invokeTaskDlgt: [ZoneDelegate],
      _invokeTaskCurrZone: [Circular],
      _cancelTaskZS: [Object],
      _cancelTaskDlgt: [ZoneDelegate],
      _cancelTaskCurrZone: [Circular],
      _hasTaskZS: [Object],
      _hasTaskDlgt: [ZoneDelegate],
      _hasTaskDlgtOwner: [Circular],
      _hasTaskCurrZone: [Circular]
    }
  },
  task: ZoneTask {
    _zone: Zone {
      _parent: [Zone],
      _name: 'angular',
      _properties: [Object],
      _zoneDelegate: [ZoneDelegate]
    },
    runCount: 0,
    _zoneDelegates: null,
    _state: 'notScheduled',
    type: 'microTask',
    source: 'Promise.then',
    data: ZoneAwarePromise [Promise] {
      __zone_symbol__state: 0,
      __zone_symbol__value: TypeError: Cannot read property 'getHeader' of null
          at ngx_cookie_backend_CookieBackendWriterService.getNormalizedResponseCookies (/Volumes/Work/Work/Projects/xyz/dist/xyz/server/main.js:1:3061602)
          at ngx_cookie_backend_CookieBackendWriterService.readAllAsString (/Volumes/Work/Work/Projects/xyz/dist/xyz/server/main.js:1:3061405)
          at CookieService.getAll (/Volumes/Work/Work/Projects/xyz/dist/xyz/server/main.js:1:403976)
          at CookieService.get (/Volumes/Work/Work/Projects/xyz/dist/xyz/server/main.js:1:403284)
          at ReferralService.get (/Volumes/Work/Work/Projects/xyz/dist/xyz/server/main.js:1:414706)
          at GuardService.canActivate (/Volumes/Work/Work/Projects/xyz/dist/xyz/server/main.js:1:415071)
          at /Volumes/Work/Work/Projects/xyz/dist/xyz/server/main.js:1:3642110
          at Observable_Observable._subscribe (/Volumes/Work/Work/Projects/xyz/dist/xyz/server/main.js:1:859887)
          at Observable_Observable._trySubscribe (/Volumes/Work/Work/Projects/xyz/dist/xyz/server/main.js:1:745882)
          at Observable_Observable.subscribe (/Volumes/Work/Work/Projects/xyz/dist/xyz/server/main.js:1:745664)
    },
    scheduleFn: undefined,
    cancelFn: undefined,
    callback: [Function],
    invoke: [Function]
  }
}
```

**Environment:**
```
Angular CLI: 11.2.3
Node: 12.18.4
OS: darwin x64

Angular: 11.2.4
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1102.3
@angular-devkit/build-angular      0.1102.3
@angular-devkit/build-ng-packagr   0.1002.0
@angular-devkit/core               11.2.3
@angular-devkit/schematics         11.2.3
@angular/cdk                       11.2.3
@angular/cli                       11.2.3
@angular/flex-layout               11.0.0-beta.33
@angular/material                  11.2.3
@nguniversal/builders              11.2.1
@nguniversal/express-engine        11.2.1
@schematics/angular                8.3.29
@schematics/update                 0.1102.3
ng-packagr                         11.2.4
rxjs                               6.6.6
typescript                         4.1.5
```

**Additional context**
In `ng serve` mode I have no any errors. Only universal prerender fails.

**Comment by pavankjadda** [comment]
@kuncevic [ngx-cookie-service](https://github.com/stevermeister/ngx-cookie-service) library maintainer here. We keep our library up to date and released support for Angular 13 as well. Feel free to give it a shot and let us know if it works for you
