### ISSUE TITLE
Angular Universal throwing NotYetImplemented

### ISSUE THREAD

**Issue by ermamud** [salemdar/ngx-cookie#383]
**Describe the bug**
I am using `ngx-cookie` latest version with Angular Universal. I already did the backend configuration to use cookies on Server-side and it was working fine until I started consuming cookies in AuthGuards or inside the NgOnInit hook from Angular components.

This is the error I am seeing in the console:

```
ERROR Error: NotYetImplemented
    at Document.exports.nyi (PATH/dist/website/server/main.js:173308:9)
    at CookieWriterService.readAllAsString (PATH/dist/website/server/main.js:204460:30)
    at CookieService.getAll (PATH/dist/website/server/main.js:204393:55)
    at CookieService.get (PATH/dist/website/server/main.js:204367:27)
    at CookieService.getObject (PATH/dist/website/server/main.js:204377:28)
    at AuthUserService.GetAuthUser (PATH/dist/website/server/main.js:231514:41)
    at AuthUserService.GetUserData (PATH/dist/website/server/main.js:231542:27)
    at ProfileComponent.GetUserData (PATH/dist/website/server/879.js:2247:33)
    at ProfileComponent.ngOnInit (PATH/dist/website/server/879.js:2153:23)
    at callHook (PATH/dist/website/server/main.js:50236:22)
```

The NotYetImplemented error is coming from `nyi` inside domino package, not sure if this is a dependency from `ngx-cookie`. Any idea how to resolve this error?

Thanks,
Ernesto

**Comment by robjean9** [comment]
Hi @ermamud did you fix you issue?

**Comment by wozniakm** [comment]
Any news on that? I see that it's still happening in version 6.0.0.

**Comment by pavankjadda** [comment]
@ermamud @wozniakm @robjean9 I am one of the maintainer of [ngx-cookie-service](https://github.com/stevermeister/ngx-cookie-service#server-side-rendering=). We recently added support for SSR (Angular Universal). Please check it out.

**Comment by salemdar** [comment]
It is most likely unrelated to this library. It is a deep dependency from angular itself:
```
=> Found "domino@2.1.6"
info Reasons this module exists
   - "@angular#platform-server" depends on it
   - Hoisted from "@angular#platform-server#domino"
```
