### ISSUE TITLE
Error: No provider for CookieService! while doing ng test

### ISSUE THREAD

**Issue by ds-manish** [salemdar/ngx-cookie#9]
**Error: No provider for CookieService! while doing ng test**  (check one with "ng test")
```
Error: No provider for CookieService!
            at injectionError (webpack:///~/@angular/core/@angular/core.es5.js:1231:21 <- src/test.ts:1538:86)
            at noProviderError (webpack:///~/@angular/core/@angular/core.es5.js:1269:0 <- src/test.ts:1576:12)
```

* **Angular version:** 1.0.0

* **Angular version:** 4.1.2
 
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by AngryCMOS** [comment]
Try using CookieModule.forRoot() in NgModule module imports array.

**Comment by softmonkeyjapan** [comment]
I was having the same issue and this is how I solved it. You should import `CookieModule.forRoot()` in your test. Here is a part of my code:

```ts
import { TestBed, async, inject } from '@angular/core/testing';

import { CookieModule, CookieService } from 'ngx-cookie';

import { AuthService } from './auth.service';
import { Session } from './session.service';

describe('AuthService', () => {
  beforeEach(() => {
    TestBed.configureTestingModule({
      imports: [
        CookieModule.forRoot() // <==== This line fixed it
      ],
      providers: [
        AuthService,
        CookieService,
        Session
      ]
    });
  })

  describe('setCookieWith', () => {
    const snapshot = new Date();

    it('sets a cookie',
      async(inject([AuthService, CookieService], (auth, cookies) => {
        spyOn(cookies, 'put');

        auth.setCookieWith('123456789', '86400');
        expect(cookies.put).toHaveBeenCalled();
      })
    ));
  });
});
```
